typography_spectrum: 0.71940465294756
color:
  brandStrength: 0.6410490754060447
  lightness: 0.09479623683728278
  saturation: 0.19675381481647491
  rhythmicContrast: 0.37135940860025585
  brandColors:
    - '#030200'
    - '#DFA94F'
    - '#C48826'
    - '#5F472D'
    - '#711508'
layout_spectrum: 0.08606983511708677
name: Christopher_DeRenzo
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: South Beach
    id: 3b4268e7-e18b-4ad8-8b2e-e35864c171f3
    type: content
title: Christopher DeRenzo
content: []
description: Professional Blog
github: true
