typography_spectrum: 0.40773010928976805
color:
  brandStrength: 0.6759890742990013
  lightness: 0.3531884355092476
  saturation: 0.08305450700297214
  rhythmicContrast: 0.34265632458446127
  brandColors:
    - '#000000'
    - '#522A0F'
    - '#3B0D05'
    - '#BC9E86'
    - '#7F604D'
github: true
layout_spectrum: 0.8956343111486202
name: Christopher_DeRenzo
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: 'Prototype Conveyor System '
    id: 1f209584-44a1-4b7d-b779-7651be8b9c87
    type: content
  - name: Live Productions
    id: fa106f05-bd7b-45dd-99c7-9e2c0bd6a239
    type: content
  - name: Woodwork
    id: 6d50d805-0c61-49d1-86a8-b20c274aa973
    type: content
  - name: South Beach
    id: 3b4268e7-e18b-4ad8-8b2e-e35864c171f3
    type: content
title: Christopher DeRenzo
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/a34a9e1e-b726-4a4e-b6aa-2983068f1c68.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/a34a9e1e-b726-4a4e-b6aa-2983068f1c68.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Professional Blog
